apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-container
        image: my-node-app-image:latest
        ports:
        - containerPort: 13001  # コンテナ内でリッスンするポートを13001に指定
        envFrom:
        - configMapRef:
            name: my-app-config
        - secretRef:
            name: my-app-secret
        volumeMounts:
        - name: google-service-account-volume
          mountPath: /etc/credentials
          readOnly: true
      volumes:
      - name: google-service-account-volume
        secret:
          secretName: google-service-account
