apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-node-app-route
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: external-http
  hostnames:
  - "x.x.com"
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    backendRefs:
    - name: my-node-app
      port: 80  # Serviceのポートに一致させる
